### ISSUE TITLE
Website should be served over HTTPS

### ISSUE THREAD

**Issue by shushugah** [railsdiff/railsdiff#13]
This service is absolutely fantastic! ♥ For security/performance reasons I am wondering if there are plans to introduce SSL.

**Comment by jswanner** [comment]
@shushugah, thanks for the kind words, and I appreciate your concern. I've been thinking about this for a while. If it were free for me to have the app be under HTTPS then I would do it in a heartbeat -- would have done it long ago. Since that's not the case, I'm less inclined to do it.

Up to this point, building and running the site has only cost me my time, and incredibly little of that, I'm very hesitant to begin paying money every month just for TLS.

**Comment by olivierlacan** [comment]
@jswanner We can use CloudFlare and do this for free. Only problem is CloudFlare tends to be aggressive about their CAPTCHA crap for Tor and VPN users.

**Comment by shushugah** [comment]
what's the source for this? Netlify can also be the host provider, and they offer free domain provisioning through Let's Encrypt. I've used both Cloudflare and namecheap as the domain provider

**Comment by andreynering** [comment]
I also love this project, thanks for making it! ❤️ 

I'd consider Netlify, it's a great and free tool for static stuff.

**Comment by jswanner** [comment]
Unfortunately, I don't believe Netlify is really a possible solution, at least not a full solution. Yes it could be used to host this Ember app, but the Ember app sends requests to the API at http://api.railsdiff.org. The API would also need to use HTTPS, but it's not a static application.

**Comment by nbibler** [comment]
As of yesterday, the site is now served from Netlify via HTTPS and the diff data backing it is, as well.

**Comment by olivierlacan** [comment]
Hot

**Comment by shushugah** [comment]
I always love seeing an old issue get closed, because it was positively addressed ♥️ thanks ya'll!

**Comment by nbibler** [comment]
Happy to do it. 😄
