### ISSUE TITLE
Diff for configuring different options on same Rails Version

### ISSUE THREAD

**Issue by AhmedKamal20** [railsdiff/railsdiff#14]
Like something to list the difference between running this command:
`rails new blog`
and this one:
`rails new blog  --skip-sprockets`

This will help to:
- Understand what you are enabling/disabling more.
- Make you know what to do if you decided in the future to revert the initial toggle you made.

I find my self creating the two apps and comparing them manually a lot, is anyone else find themselves in the situation?

**Comment by jswanner** [comment]
@AhmedKamal20, thanks for your suggestion.

Unfortunately, I don't think this is the path that I want to take this project. Mainly, that is because I see this project as a tool to use while upgrading an existing Rails application, by comparing the default generated application across different Rails versions; whereas your suggestion is more about comparing the result of generating an application given different options within the same Rails version. Additionally, there are so many options that `rails new` can be given, and those options change from version to version, keeping track of what options each version supports and what options make sense to compare across versions is not something I care to do -- I also think adding such a thing would make for a confusing user interface.
