### ISSUE TITLE
Rails 6.1.4.4 - 7.0.0 diff: bin/importmap is not displayed 

### ISSUE THREAD

**Issue by taketo1113** [railsdiff/railsdiff#242]
`bin/importmap` is not displayed in Rails `6.1.4.4` - `7.0.0` diff.

- Rails 6.1.4.4 - 7.0.0 diff
  - https://railsdiff.org/6.1.4.4/7.0.0

I guess that files in `railsdiff/rails-new-output` are different from `rails new` with ver 7.0.0.
For that reason, I have created the below PR for `railsdiff/rails-new-output`.

- https://github.com/railsdiff/rails-new-output/pull/1

**Comment by jswanner** [comment]
@taketo1113, thanks for opening up an issue and creating the PR.

I might be wrong on this (I don't have any experience with Rails 7 yet), but it seems that `bin/importmap` is created by running `rails importmap:install` in an existing rails app (even if newly created) and is not created as part of `rails new`. Assuming that's the case, then it seems it shouldn't be included in the diffs as that's an optional thing that's been installed in the apps.

**Comment by taketo1113** [comment]
@jswanner thanks for a comment.

> but it seems that `bin/importmap` is created by running `rails importmap:install` in an existing rails app (even if newly created) and is not created as part of `rails new`.

That means, is `rails-new-output` created by `rails new` with `--skip-bundle` options?

Even if it uses `--skip-bundle` option, it seems that some files be wrong.
Because `package.json` and some files of `config/initializers/*` should be removed when `rails new`.

FYI: I updated PR with `--skip-bundle` option.

**Comment by jswanner** [comment]
Ah crap... Since we switched from https://github.com/railsdiff/api to using GitHub as the API with this repo, I haven't completely automated the process of adding a new Rails release. For the 9 releases this past week, I forgot to delete all the files in the directory before replacing with the next release's contents, thereby missing if files were deleted. 

Again, thanks for reporting the issue. Unfortunately, I can't really use PRs for this repo, as I need to rewrite history and delete/recreate tags and other destructive stuff you don't normally want to do in a repository.

**Comment by jswanner** [comment]
@taketo1113, this should now be resolved. The files were removed back with [v7.0.0.alpha1](https://railsdiff.org/6.1.4.4/7.0.0.alpha1). I needed to remove them from that tag, so that all the prerelease versions of v7.0.0 would generate the correct diff. Thanks again for pointing this out.

**Comment by taketo1113** [comment]
Thank you for fix it! I confirmed that it was fixed at railsdiff.org.
It was very helpful because I always use when i upgrade rails version.
