### ISSUE TITLE
Add rails-3-2-stable branch

### ISSUE THREAD

**Issue by Trevoke** [railsdiff/railsdiff#3]
The end-of-life branch for Rails 3 fixes some bugs, notably some things about using Ruby 2.2, and it would be nice to be able to use that in the comparisons.

**Comment by nbibler** [comment]
Is there some particular version that is missing? Below is a screenshot of all of the currently-diffable 3.2.x Rails versions, spanning `3.2.0.rc1` to `3.2.22.5`:

![Diffable Rails 3.2.x Versions](https://user-images.githubusercontent.com/3775/112725560-399f4800-8eef-11eb-94f8-452dbb145f60.png)

Since this project merely tracks released versions of Rails, I'm going to close this ticket. If there are unidentified versions, please open a specific ticket to get them added to the project.

Thanks!
