### ISSUE TITLE
Rails 4.2.2 - 5.0.0.1 diff: cable.js line 16: wrong relative path

### ISSUE THREAD

**Issue by knzudgt** [railsdiff/railsdiff#5]
Line 6 of `app/assets/javascripts/cable.js` in `Rails 4.2.2 - 5.0.0.1 diff` raises an error (`channels` should be a directory). Line 6 is:

`//= require_tree ./channels`

Also, according to Cloud9 editor, `ActionCable` in `app/assets/javascripts/cable.js` results not defined: `ActionCable is not defined; please fix or add /*global ActionCable*/`

**Comment by knzudgt** [comment]
Apparently railsdiff does not consider and report empty directories.
In rails 5.0.0.1, compared to rails 4.2.2, there are two new empty directories with an hidden, empty `.keep` file inside each one:

```
app/assets/javascripts/channels/
test/fixtures/files/
```

Line 6 of `app/assets/javascripts/cable.js` refers to `app/assets/javascripts/channels/`.
Running the test suite without adding the `channels` directory would raise an error.

**Comment by jswanner** [comment]
RailsDiff is basically just a web-based visualizer for the [*nix `diff` utility][diff]. The crux of the problem is that the new directories only contain empty (`.keep`) files; the way I'm currently invoking `diff`, comparing a non-existent directory to a directory with an empty file produces no output. The diff utility has many arguments that can be applied to change how it operates and what it outputs, but I cannot find a way to solve this problem.

Take this example scenario:

```
$ tree
.
├── a/
│   └── .keep
└── b/
    ├── c/
    │   └── .keep
    └── foo

3 directories, 3 files
```

When I run `diff` the way the RailsDiff API currently does, this is the result:

```
$ diff -N -r -u a b
diff -N -r -u a/foo b/foo
--- a/foo       1969-12-31 16:00:00.000000000 -0800
+++ b/foo       2017-06-13 11:13:51.000000000 -0700
@@ -0,0 +1 @@
+bar
```

As you can see, there's nothing in the output about the empty `.keep` files.

I can run it slightly differently, which lets me know about `a/.keep`:

```
$ diff --unidirectional-new-file -r -U 1000 a b
Only in a: .keep
diff --unidirectional-new-file -r -U 1000 a/foo b/foo
--- a/foo       1969-12-31 16:00:00.000000000 -0800
+++ b/foo       2017-06-13 11:13:51.000000000 -0700
@@ -0,0 +1 @@
+bar
```

Running it that way would only help if a directory were removed in later versions of Rails, but wouldn't help in your situation that Rails added directories.

For the sake of completeness, here's another way to run `diff`, which is the only way I've found for it to show the existence of `b/c`, but it doesn't include the content of `b/foo` so it is not useful:

```
$ diff -r -u a b
Only in a: .keep
Only in b: c
Only in b: foo
```
[diff]: http://man7.org/linux/man-pages/man1/diff.1.html

**Comment by jswanner** [comment]
At the end of the day, RailsDiff should just be a tool you use to help when upgrading the version of Rails your application is using, but it shouldn't be the only tool you use. It is not a complete replacement for the tools that Rails itself provides when upgrading your application; I would still run `rails app:update` (or `rake rails:update` for older versions), even if it's just to use its <kbd>d</kbd> option to view differences.
