### ISSUE TITLE
Rails 7.0.7.2 - 7.0.8 diff: Omit webdrivers gem from Gemfile is not displayed

### ISSUE THREAD

**Issue by taketo1113** [railsdiff/railsdiff#581]
Rails v7.0.8 omits the webdrivers gem from Gemfile template.
But this diff is not displayed.

- Rails 7.0.7.2 - 7.0.8 diff
  - https://railsdiff.org/7.0.7.2/7.0.8
- Release note: rails v7.0.8
  - https://github.com/rails/rails/releases/tag/v7.0.8
  - https://github.com/rails/rails/blob/v7.0.8/railties/lib/rails/generators/rails/app/templates/Gemfile.tt#L66-L68

It seems that the cause is using ruby 2.7.4 in `railsdiff/rails-new-output`.
https://github.com/railsdiff/rails-new-output/blob/main/Gemfile#L4

I think it is better to use ruby 3.0+ in `railsdiff/rails-new-output`, because Ruby 2.7 was supported until 2023-03-31.

- Ruby Maintenance Branches
  - https://www.ruby-lang.org/en/downloads/branches/

**Comment by jswanner** [comment]
Hey @taketo1113, thanks for reporting this.

> I think it is better to use ruby 3.0+ in `railsdiff/rails-new-output`, because Ruby 2.7 was supported until 2023-03-31.

Yeah, I agree. I had been putting off upgrading the version of Ruby that I use to generate the applications, because I didn't want that Ruby version change to show up in the diffs. I also hadn't gotten around to modifying my generation script to replace the Ruby version I had used to generate the application with a stand-in value (like `"RUBY_VERSION"`), mostly because I was putting off the work of retroactively fixing all the old generated apps.

**Comment by taketo1113** [comment]
@jswanner Thanks for replay.
Please let me know and I will help to update a script, if you need it.

RailsDiff helps me every time when I update rails :-)

**Comment by jswanner** [comment]
This has been fixed, thanks again for reporting it.

**Comment by taketo1113** [comment]
Thanks to fix. It seems to be working fine.
